@startuml

' == THEME ==

skinparam RoundCorner 10
'skinparam sequenceArrowThickness 2

' == CONTENT ==

entity "Card" as card
participant "Terminal" as client
participant "Server" as server

activate card #LightGrey
card --\ client : a card is inserted

activate client #LightGrey
client -[#3498DB]> server : <color: #3498DB>message (**{** **EXECUTE_REMOTE_SERVICE**, transaction input data **}**, ...)

activate server #LightGrey

loop #EFEFEF while there are actions to be performed with the card or the terminal's reader
    server -[#27AE60]-> client : <color:#27AE60>message (**[{** **CMD**, action **}]**, ...)
    client -> card : process (action)
    card --> client : result
    client -[#3498DB]> server : <color: #3498DB>message (**{** **RESP**, result **}**, ...)
end

server -[#27AE60]-> client : <color:#27AE60>message (**[{** **END_REMOTE_SERVICE**, transaction output data **}]**, ...)
deactivate server

card --\ client : the card is removed
deactivate card

@enduml