@startuml

' == THEME ==

skinparam RoundCorner 10
'skinparam sequenceArrowThickness 2

' == CONTENT ==

entity "Card" as card
participant "Terminal" as client
participant "Server" as server

activate card #LightGrey
card --\ client : a card is inserted

activate client #LightGrey
client -[#red]> server : JSON (**EXECUTE_REMOTE_SERVICE**, transaction input data)

activate server #LightGrey

loop #EFEFEF while there are actions to be performed with the card or the terminal reader
    server -[#blue]-> client : JSON (**CMD**, action)
    client -[#red]> card : process (action)
    card -[#blue]-> client : result
    client -[#red]> server : JSON (**RESP**, result)
end

server -[#blue]-> client : JSON (**END_REMOTE_SERVICE**, transaction output data)
deactivate server

card --\ client : the card is removed
deactivate card

@enduml