@startuml

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define COLOR_YELLOW D4AC0D
!define COLOR_RED E74C3C
!define COLOR_PURPLE 8E44AD
!define COLOR_BLUE 3498DB
!define COLOR_GREEN 27AE60
!define COLOR_GREY 2C3E50

!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60

skinparam Shadowing false
skinparam component {
    BorderColor #D4AC0D
    ' Red
    BackgroundColor<<red>> #FDEDEC
    BorderColor<<red>> #E74C3C
    ' Purple
    BackgroundColor<<purple>> #F4ECF7
    BorderColor<<purple>> #8E44AD
    ' blue
    BackgroundColor<<blue>> #EBF5FB
    BorderColor<<blue>> #3498DB
    ' Green
    BackgroundColor<<green>> #E9F7EF
    BorderColor<<green>> #27AE60
    ' Grey
    BackgroundColor<<grey>> #EAECEE
    BorderColor<<grey>> #2C3E50
}
skinparam interface {
    BorderColor #D4AC0D
    ' Red
    BackgroundColor<<red>> #FDEDEC
    BorderColor<<red>> #E74C3C
    ' Purple
    BackgroundColor<<purple>> #F4ECF7
    BorderColor<<purple>> #8E44AD
    ' blue
    BackgroundColor<<blue>> #EBF5FB
    BorderColor<<blue>> #3498DB
    ' Green
    BackgroundColor<<green>> #E9F7EF
    BorderColor<<green>> #27AE60
    ' Grey
    BackgroundColor<<grey>> #EAECEE
    BorderColor<<grey>> #2C3E50
}
hide <<red>> stereotype
hide <<purple>> stereotype
hide <<blue>> stereotype
hide <<green>> stereotype
hide <<grey>> stereotype

' == COMPONENTS ==

[Client Application] as application <<blue>>
package "Plugin Xxx" as packPlugin {
    interface " " as specificPluginApi <<green>>
    [Adapter] as plugin <<green>>
}
package "Common API" as packCommonApi {
    interface " " as commonApi <<green>>
}
package "Keyple Service" as packService {
    interface " " as serviceApi
    [Adapter] as service
}
package "Plugin API" as packPluginApi {
    interface "API" as pluginApi
    interface "SPI" as pluginSpi <<green>>
}

' == ASSOCIATIONS ==

plugin -up- commonApi #COLOR_GREEN
plugin -up- specificPluginApi #COLOR_GREEN
plugin -- pluginSpi #COLOR_GREEN

service -up- serviceApi #COLOR_YELLOW
service -- pluginApi #COLOR_YELLOW

' USE

application ..> commonApi : use
application ..> specificPluginApi : use
application ..> serviceApi : use

serviceApi .right.> commonApi : "  use          "
service ..> pluginSpi : use

plugin ..> pluginApi : use

' == LAYOUT ==

service .[hidden]up.> commonApi

' == STYLE ==

package packPlugin #C_GREY1 {
}
package packService #C_GREY1 {
}
package packCommonApi #C_GREY1 {
}
package packPluginApi #C_GREY1 {
}

@enduml