'---------------------------------------------------------------------------------
' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Eclipse Public License 2.0 which is available at
' http://www.eclipse.org/legal/epl-2.0
'
' SPDX-License-Identifier: EPL-2.0 4
'---------------------------------------------------------------------------------

@startuml
!include Keyple_ClassDiag_PlantUmlSetting.iuml

package specific.terminal_application #85C1E9 {
  class SpecificTerminal
}

package org.eclipse.keyple.core.service #FFFFFF {
'  package service #FFFFFF {
    !include KeypleCore_Reader_ClassDiag_ClassElements.iuml!READER_SERVICE_1_0_0
    !include KeypleCore_Reader_ClassDiag_ClassElements.iuml!READER_PLUGIN_1_0_0
    !include KeypleCore_Reader_ClassDiag_ClassElements.iuml!READER_READER_1_0_0
    !include KeypleCore_Plugin_ClassDiag_ClassElements.iuml!PLUGIN_FACTORY_1_0_0

    package util #FFFFFF {
      !include KeypleCore_Reader_ClassDiag_ClassElements.iuml!READER_UTIL_1_0_0
    }

    SmartCardService "1" *-down-> "*" Plugin : plugins
    Plugin "1" *-left-> "*" Reader : readers
    ContactlessCardCommonProtocols -right[hidden]- SmartCardService
    ContactlessCardCommonProtocols -down- Reader : application\nprotocol\nreference >
'  }
'  package plugin.setting #FFFFFF {
'    !include KeypleCore_Plugin_ClassDiag_ClassElements.iuml!PLUGIN_FACTORY_1_0_0
'  }

'  plugin.setting -left[hidden]- reader
  SmartCardService "1" <-right- "*" PluginFactory : sets <
  PluginFactory "1" --> "1" Plugin : creates >
}

!include KeypleCore_Reader_ClassDiag_ClassElements.iuml!READER_SPECIFICPLUGIN_1_0_0
SpecificTerminal -down-> SmartCardService : uses >

Plugin <|.down. SpecificPlugin : implements
Reader <|.down. SpecificReader : implements
PluginFactory <|.down. SpecificPluginFactory : implements
Reader -- SpecificSupportedProtocols : plugin\nprotocol\nreference <
@enduml
