@startuml

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define COLOR_YELLOW D4AC0D
!define COLOR_RED E74C3C
!define COLOR_PURPLE 8E44AD
!define COLOR_BLUE 3498DB
!define COLOR_GREEN 27AE60
!define COLOR_ORANGE E67E22
!define COLOR_GREY 2C3E50
skinparam Shadowing false
skinparam component {
    BorderColor #D4AC0D
    ' Red
    BackgroundColor<<red>> #FDEDEC
    BorderColor<<red>> #E74C3C
    ' Purple
    BackgroundColor<<purple>> #F4ECF7
    BorderColor<<purple>> #8E44AD
    ' blue
    BackgroundColor<<blue>> #EBF5FB
    BorderColor<<blue>> #3498DB
    ' Green
    BackgroundColor<<green>> #E9F7EF
    BorderColor<<green>> #27AE60
    ' Orange
    BackgroundColor<<orange>> #FDF2E9
    BorderColor<<orange>> #E67E22
    ' Grey
    BackgroundColor<<grey>> #EAECEE
    BorderColor<<grey>> #2C3E50
}
skinparam interface {
    BorderColor #D4AC0D
    ' Red
    BackgroundColor<<red>> #FDEDEC
    BorderColor<<red>> #E74C3C
    ' Purple
    BackgroundColor<<purple>> #F4ECF7
    BorderColor<<purple>> #8E44AD
    ' blue
    BackgroundColor<<blue>> #EBF5FB
    BorderColor<<blue>> #3498DB
    ' Green
    BackgroundColor<<green>> #E9F7EF
    BorderColor<<green>> #27AE60
    ' Orange
    BackgroundColor<<orange>> #FDF2E9
    BorderColor<<orange>> #E67E22
    ' Grey
    BackgroundColor<<grey>> #EAECEE
    BorderColor<<grey>> #2C3E50
}
hide <<red>> stereotype
hide <<purple>> stereotype
hide <<blue>> stereotype
hide <<green>> stereotype
hide <<orange>> stereotype
hide <<grey>> stereotype

' == CONTENT ==

[Hardware Reader\n(Card, SAM, HSM,...)] as reader <<red>>

package "Terminal with local reader" #C_GREY1 {
    [Application] as appA
    package "Keyple" as localKeyple #C_GREY2 {
        [Keyple Core Services\n + Card Extension\n + Reader Plugin] as localKeypleLibs <<purple>>
        [**Keyple Distributed**\n(**local** components)] as localLib <<blue>>
    }
    [Network Endpoint] as endpointA <<green>>
}

package "Terminal without local reader" #C_GREY1 {
    [Application] as appB
    package "Keyple" as remoteKeyple #C_GREY2 {
        [Keyple Core Services\n + Card Extension] as remoteKeypleLibs <<purple>>
        [**Keyple Distributed**\n(**remote** components)] as remoteLib <<blue>>
    }
    [Network Endpoint] as endpointB <<green>>
}

reader - localKeypleLibs

appA -- localKeypleLibs
appA -- localLib
localKeypleLibs - localLib
localLib -- endpointA

endpointA - endpointB

appB -- remoteKeypleLibs
appB -- remoteLib
remoteKeypleLibs -left- remoteLib
remoteLib -- endpointB

@enduml