name: External Resources Proposal Form
description: Fill out this form to provide information about the external resources to be referenced.
  Please use the english language.
title: "External Resources Proposal"
labels: ["resource"]
body:
  - type: markdown
    attributes:
      value: |
        ## Supplier
  - type: input
    attributes:
      label: Name of the company that provides the resources
    validations:
      required: true
  - type: input
    attributes:
      label: Company website
    validations:
      required: true
  - type: textarea
    attributes:
      label: Company logo
      description: |
        **Provide your company logo to be listed as an adopter on the Eclipse Foundation website.**
        Important: Please attach your logos in svg or png format, zipped if svg.
        Please note that we require both color options for logos for distribution purposes. 
        - We need color logo with transparent background.
        - We also need white logo with a transparent background.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        <br>

        ## Provided resource types
  - type: dropdown
    attributes:
      label: Types of products or services provided (multiple options can be selected)
      multiple: true
      options:
        - Reader plugins
        - Card extensions
        - Demos
        - Tools
        - Compliant terminals
        - Training
        - Development
  - type: input
    attributes:
      label: Other types (not listed above)
      placeholder: R1, R2, etc.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        <br>

        ## Short description
  - type: input
    attributes:
      label: Short description (sentence 1)
    validations:
      required: true
  - type: input
    attributes:
      label: Short description (sentence 2, optional)
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        <br>

        ## Full description
  - type: input
    attributes:
      label: External page URL
    validations:
      required: false
  - type: markdown
    attributes:
      value: "or"
  - type: textarea
    attributes:
      label: Rich text description
    validations:
      required: false
