@startuml
footer
    Keyple Remote Plugin - Concepts - Complex Use Case (29/10/2020)
end footer

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define COLOR_RED E74C3C
!define COLOR_PURPLE 8E44AD
!define COLOR_BLUE 3498DB
!define COLOR_GREEN 27AE60
!define COLOR_GREY 2C3E50
skinparam Shadowing false
skinparam component {
    BorderColor #D4AC0D
    ' Red
    BackgroundColor<<red>> #FDEDEC
    BorderColor<<red>> #E74C3C
    ' Purple
    BackgroundColor<<purple>> #F4ECF7
    BorderColor<<purple>> #8E44AD
    ' blue
    BackgroundColor<<blue>> #EBF5FB
    BorderColor<<blue>> #3498DB
    ' Green
    BackgroundColor<<green>> #E9F7EF
    BorderColor<<green>> #27AE60
    ' Grey
    BackgroundColor<<grey>> #EAECEE
    BorderColor<<grey>> #2C3E50
}
hide <<red>> stereotype
hide <<purple>> stereotype
hide <<blue>> stereotype
hide <<green>> stereotype
hide <<grey>> stereotype

' == CONTENT ==

[Hardware Reader A\n(PO, SAM, HSM,...)] as readerA <<green>>
[Hardware Reader B\n(PO, SAM, HSM,...)] as readerB <<blue>>
[Hardware Reader C\n(PO, SAM, HSM,...)] as readerC <<purple>>
package "Terminal A with 'hardware' reader" {
    [Application] as appA
    [**Native Service**] as nativeServiceA <<red>>
    [Native\nPlugin A] as nativePluginA <<green>>
    [Native\nReader A] as nativeReaderA <<green>>
}
package "Terminal with 'virtual' reader" {
    [Application] as app
    [**Remote Plugin**] as remotePlugin <<red>>
    [Virtual\nReader A] as virtualReaderA <<green>>
    [Virtual\nReader B] as virtualReaderB <<blue>>
    [Virtual\nReader C] as virtualReaderC <<purple>>
}
package "Terminal B with 'hardware' reader" {
    [Application] as appB
    [**Native Service**] as nativeServiceB <<red>>
    [Native\nPlugin B] as nativePluginB <<blue>>
    [Native\nReader B] as nativeReaderB <<blue>>
    [Native\nPlugin C] as nativePluginC <<purple>>
    [Native\nReader C] as nativeReaderC <<purple>>
}

'utilisation

appA -- nativePluginA #LightGrey
appA -- nativeReaderA #LightGrey
appA -- nativeServiceA
nativePluginA -- nativeReaderA #COLOR_GREEN
nativeServiceA -- nativePluginA #COLOR_GREEN
nativeServiceA -- nativeReaderA #COLOR_GREEN
nativeReaderA -- readerA #COLOR_GREEN

nativeServiceA - remotePlugin

app -- remotePlugin
app -- virtualReaderA #LightGrey
app -- virtualReaderB #LightGrey
app -- virtualReaderC #LightGrey
remotePlugin -- virtualReaderA #COLOR_GREEN
remotePlugin -- virtualReaderB #COLOR_BLUE
remotePlugin -- virtualReaderC #COLOR_PURPLE

remotePlugin - nativeServiceB

appB -- nativePluginB #LightGrey
appB -- nativeReaderB #LightGrey
appB -- nativeServiceB
nativePluginB -- nativeReaderB #COLOR_BLUE
nativeServiceB -- nativePluginB #COLOR_BLUE
nativeServiceB -- nativeReaderB #COLOR_BLUE
nativeReaderB -- readerB #COLOR_BLUE

appB -- nativePluginC #LightGrey
appB -- nativeReaderC #LightGrey
nativeServiceB -- nativePluginC #COLOR_PURPLE
nativeServiceB -- nativeReaderC #COLOR_PURPLE
nativePluginC -- nativeReaderC #COLOR_PURPLE
nativeReaderC -- readerC #COLOR_PURPLE

@enduml