@startuml
title
    UC 4: RemoteClientPlugin - ObservableReader (07/10/2020)
end title

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
skinparam Shadowing false
skinparam component {
    BorderColor #D4AC0D
    ' Red
    BackgroundColor<<red>> #FDEDEC
    BorderColor<<red>> #E74C3C
    ' Purple
    BackgroundColor<<purple>> #F4ECF7
    BorderColor<<purple>> #8E44AD
    ' blue
    BackgroundColor<<blue>> #EBF5FB
    BorderColor<<blue>> #3498DB
    ' Green
    BackgroundColor<<green>> #E9F7EF
    BorderColor<<green>> #27AE60
    ' Grey
    BackgroundColor<<grey>> #EAECEE
    BorderColor<<grey>> #2C3E50
}
hide <<red>> stereotype
hide <<purple>> stereotype
hide <<blue>> stereotype
hide <<green>> stereotype
hide <<grey>> stereotype

' == CONTENT ==

package "Client App" {
    [<i>Ticketing Service</i>] as master
    package "Keyple Remote Virtual Lib" as virtualKeyple {
        [ObservableReader] as virtualReader <<blue>>
        [RemoteClientPlugin] <<green>>
    }
}
[Card]
package "Server App" {
    package "Keyple Remote Native Lib" as nativeKeyple {
        [ObservableReader] as nativeReader <<blue>>
        [Plugin] <<green>>
        [NativeServerService] <<green>>
    }
}

'utilisation
start -> master
master -> [RemoteClientPlugin]
master -> virtualReader
[RemoteClientPlugin] --> virtualReader

[RemoteClientPlugin] <-> [NativeServerService]
virtualReader -up-> [NativeServerService]

[NativeServerService] -> [Plugin]
[NativeServerService] -> nativeReader
[Plugin] --> nativeReader
nativeReader --> [Card]

virtualReader .up.> master #Blue : <color:blue>Card Event
[Card] .up.> nativeReader #Blue : <color:blue>Card Event
nativeReader .up.> [NativeServerService] #Blue : <color:blue>Card Event

@enduml