@startuml
title
    Keyple Plugin - Observable Reader Notifiers- 1.0.0 (10/11/2020)
end title

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60

skinparam Shadowing false
skinparam ClassFontStyle italic
skinparam ClassBorderColor #D4AC0D
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB93DF
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==
+interface Reader {
}

+interface ObservableReader {
}

package "org.eclipse.keyple.core.plugin" as root {

    package "reader"{

        +interface ObservableReaderNotifier {
            ~notifyObservers(final ReaderEvent event)
        }

        +interface WaitForCardInsertionAutonomous {
        }

        +interface WaitForCardInsertionBlocking {
          ~boolean waitForCardPresent()
          ~void stopWaitForCard()
        }

        +interface WaitForCardInsertionNonBlocking {
        }

        +interface WaitForCardRemovalAutonomous {
        }

        +interface WaitForCardRemovalBlocking {
          ~boolean waitForCardAbsentNative()
          ~void stopWaitForCardRemoval()
        }

        +interface WaitForCardRemovalNonBlocking {
        }

        +interface DontWaitForCardRemovalDuringProcessing {
        }

        +interface WaitForCardRemovalDuringProcessing {
        }

    }
}


' Associations
Reader <|-- ObservableReader #C_USE
ObservableReader <|-- ObservableReaderNotifier #C_USE
ObservableReaderNotifier <|-- WaitForCardInsertionAutonomous #C_USE
ObservableReaderNotifier <|-- WaitForCardInsertionBlocking #C_USE
ObservableReaderNotifier <|-- WaitForCardInsertionNonBlocking #C_USE
ObservableReaderNotifier <|-- WaitForCardRemovalAutonomous #C_USE
ObservableReaderNotifier <|-- WaitForCardRemovalBlocking #C_USE
ObservableReaderNotifier <|-- WaitForCardRemovalNonBlocking #C_USE
ObservableReaderNotifier <|-- DontWaitForCardRemovalDuringProcessing #C_USE
ObservableReaderNotifier <|-- WaitForCardRemovalDuringProcessing #C_USE

@enduml