'---------------------------------------------------------------------------------
' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Eclipse Public License 2.0 which is available at
' http://www.eclipse.org/legal/epl-2.0
'
' SPDX-License-Identifier: EPL-2.0 4
'---------------------------------------------------------------------------------

@startuml
!include Keyple_ClassDiag_PlantUmlSetting.iuml

package org.keyple.calypso #FFFFFF {
  package transaction #FFFFFF {
    !include KeypleCalypso_Transaction_ClassDiag_ClassElements.iuml!TRANSACTION_SECURITYSETTING_1_0_0

    PoSecuritySettingBuilder .right. N1
    PoSecuritySettingBuilder -down- PoSecuritySetting : build >

    together {
      +class "SeResource<CalypsoSam>" as SamResource {
        +SeResource(<color:red>SeReader seReader</color>,
          CalypsoSam sam);
      }

      +class "<b>final</b> CalypsoSam" as CalypsoSam {
        ~CalypsoSam(<color:red>CardSelectionResponse samSelectionResponse</color>)

        +SamRevision getSamRevision()
        +byte[] getSerialNumber()
        +byte getPlatform()
        +byte getApplicationType()
        +byte getApplicationSubType()
        +byte getSoftwareIssuer()
      }
    }

    PoSecuritySetting "1 " o-right- " 0..1" SamResource
    SamResource "1" o- "1" CalypsoSam

    +class "SeResource<CalypsoPo>" as PoResource {
      +SeResource(<color:red>SeReader seReader</color>,
        CalypsoPo po);
    }

    !include KeypleCalypso_Transaction_ClassDiag_ClassElements.iuml!TRANSACTION_POTRANSACTION_0_9_0
    !include KeypleCalypso_Transaction_ClassDiag_ClassElements.iuml!TRANSACTION_POTRANSACTION_INTPARAM

    SvSetting +-down- Operation
    SvSetting +-down- Action
    SvSetting +-down- LogRead
    SvSetting +-right- NegativeBalance

    PoResource "1" --o "1" PoTransaction
    PoResource -right[hidden]- PoSecuritySetting
    PoTransaction "1" o-up- "0..1" PoSecuritySetting

    PoTransaction +-down- SessionState

    PoTransaction +-down- SessionSetting
    SessionSetting +-down- EncryptionMode
    SessionSetting +-down- ModificationMode
    SessionSetting +-down- RatificationMode
    SessionSetting +-- AccessLevel
    EncryptionMode -down[hidden]- AccessLevel
    SessionSetting +-- AuthenticationMode
    ModificationMode -down[hidden]- AuthenticationMode

    PoTransaction +-down- PinTransmissionMode
    PoTransaction +-down- SvSetting

    SessionState -right[hidden]- SessionSetting
    SessionSetting -right[hidden]- PinTransmissionMode
    PinTransmissionMode -right[hidden]- SvSetting
  }

  !include KeypleCalypso_Transaction_ClassDiag_ClassElements.iuml!TRANSACTION_POTRANSACTION_EXTPARAM
  PoTransaction -- SelectFileControl
'  PoTransaction -- ChannelControl
  AuthenticationMode -down[hidden]- SelectFileControl
'  ChannelControl -left[hidden]- SelectFileControl
}
@enduml
