'---------------------------------------------------------------------------------
' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Eclipse Public License 2.0 which is available at
' http://www.eclipse.org/legal/epl-2.0
'
' SPDX-License-Identifier: EPL-2.0 4
'---------------------------------------------------------------------------------

@startuml
!include KeypleCore_Reader_ClassDiag_ObservablePluginAndReaderEvents_shared_1_0_0.iuml
!include KeypleCore_Reader_ClassDiag_ClassElements.iuml!READER_SERVICE_1_0_0
!include KeypleCore_Reader_ClassDiag_ClassElements.iuml!READER_PLUGIN_1_0_0
!include KeypleCore_Reader_ClassDiag_ClassElements.iuml!READER_READER_1_0_0
!include KeypleCore_Reader_ClassDiag_ClassElements.iuml!READER_OBSERVABLEPLUGIN_1_0_0
!include KeypleCore_Reader_ClassDiag_ClassElements.iuml!READER_EVENTREADER_1_0_0
!include KeypleCore_Reader_ClassDiag_ClassElements.iuml!READER_OBSERVABLEREADER_1_0_0
@enduml
