@startuml

' == THEME ==

skinparam RoundCorner 10
'skinparam sequenceArrowThickness 2

' == CONTENT ==

entity "Card" as card
participant "Terminal" as client
participant "Server" as server

activate card #LightGrey
card --\ client : a card is inserted

activate client #LightGrey
client -[#3498DB]> server : <color: #3498DB>**Execute Remote Service**

activate server #LightGrey

loop #F5F5F5 while there are actions to be performed with the card or the terminal's reader
    server -[#27AE60]-> client : <color:#27AE60>**Command**
    client -> card : command
    card --> client : response
    client -[#3498DB]> server : <color: #3498DB>**Response**
end

server -[#27AE60]-> client : <color:#27AE60>**End Remote Service**
deactivate server

card --\ client : the card is removed
deactivate card

@enduml