@startuml

' == THEME ==

skinparam RoundCorner 10
'skinparam sequenceArrowThickness 2

' == CONTENT ==

entity "Card" as card
participant "Terminal" as client
participant "Server" as server

card -->> client ++ #LightGrey : card is inserted
activate card #LightGrey

client -[#3498DB]> server ++ #LightGrey : <color: #3498DB>**Execute Remote Service**

loop #F5F5F5 while there are actions to be performed with the card or the terminal's reader
    client <-[#27AE60]- server : <color:#27AE60>**Command**
    card <- client : command
    card --> client : response
    client -[#3498DB]> server : <color: #3498DB>**Response**
end

client <-[#27AE60]- server -- : <color:#27AE60>**End Remote Service**

card -->> client -- : card is removed
deactivate client
deactivate card

@enduml