@startuml
' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
skinparam Shadowing false
skinparam component {
    BorderColor #D4AC0D
    ' Red
    BackgroundColor<<red>> #FDEDEC
    BorderColor<<red>> #E74C3C
    ' Purple
    BackgroundColor<<purple>> #F4ECF7
    BorderColor<<purple>> #8E44AD
    ' blue
    BackgroundColor<<blue>> #EBF5FB
    BorderColor<<blue>> #3498DB
    ' Green
    BackgroundColor<<green>> #E9F7EF
    BorderColor<<green>> #27AE60
    ' Grey
    BackgroundColor<<grey>> #EAECEE
    BorderColor<<grey>> #2C3E50
}
hide <<red>> stereotype
hide <<purple>> stereotype
hide <<blue>> stereotype
hide <<green>> stereotype
hide <<grey>> stereotype

' == CONTENT ==

[Hardware Reader(s)] as reader <<red>>
' [Smart card] as smartcard <<green>>

package "Terminal with 'local' readers" {
    [Application] as appA
    package "Keyple" as localKeyple {
        [Keyple Core & companion modules] as localKeypleLibs <<purple>>
    }
}



appA - localKeypleLibs
localKeypleLibs - reader


@enduml