name: Build and deploy site

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements
        run: pip install requests

      - name: Update permissions
        working-directory: .
        run: chmod +x ./.github/scripts/*.sh

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.120.4'
          extended: true

      - name: Set up jq
        uses: sergeysova/jq-action@v2

      - name: Create project changelog
        working-directory: .
        run: ./.github/scripts/changelog_generate_page.sh
        continue-on-error: true

      - name: Build
        run: hugo --minify
        working-directory: ./

      - name: Init dashboard data
        working-directory: ./public
        run: ../.github/scripts/dashboard_init.sh ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch repository statistics
        working-directory: ./public
        run: python ../.github/scripts/fetch_repo_stats.py --token ${{ secrets.GITHUB_TOKEN }} --output-dir ./statistics ../.github/scripts/statistics_repos.list
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
